{ id: '685960818',
  name: 'Alvaro Muir',
  first_name: 'Alvaro',
  last_name: 'Muir',
  link: 'http://www.facebook.com/alvaromuir',
  username: 'alvaromuir',
  bio: 'I does it big',
  work: 
   [ { employer: [Object], location: [Object], position: [Object] },
     { employer: [Object],
       location: [Object],
       position: [Object],
       start_date: '0000-00',
       end_date: '0000-00' },
     { employer: [Object],
       position: [Object],
       start_date: '0000-00',
       end_date: '0000-00' },
     { employer: [Object],
       location: [Object],
       start_date: '0000-00',
       end_date: '0000-00' } ],
  education: 
   [ { school: [Object], year: [Object], type: 'High School' },
     { school: [Object],
       year: [Object],
       concentration: [Object],
       type: 'College' },
     { school: [Object],
       year: [Object],
       concentration: [Object],
       type: 'Graduate School' } ],
  gender: 'male',
  timezone: -4,
  locale: 'en_US',
  languages: [ { id: '110343528993409', name: 'Spanish' } ],
  verified: true,
  updated_time: '2012-04-23T02:58:26+0000' }