// Generated by CoffeeScript 1.7.1
(function() {
  var TodoCtrl;

  console.log('test');

  TodoCtrl = function($scope) {
    return $scope.totalTodos = 4;
  };

}).call(this);

//# sourceMappingURL=todo.map
