// Generated by CoffeeScript 1.7.1
(function() {
  var get_products_of_all_ints_except_at_index;

  get_products_of_all_ints_except_at_index = function(arr) {
    return arr;
  };

}).call(this);

//# sourceMappingURL=every_integer_except_index.map
