/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'alvaro' at '5/1/14 8:40 PM' with Gradle 1.12
 *
 * @author alvaro, @date 5/1/14 8:40 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
